# coding: utf-8

"""
    API Manager API v1.3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: support@axway.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.grant_types import GrantTypes  # noqa: F401,E501
from swagger_client.models.schema_object import SchemaObject  # noqa: F401,E501
from swagger_client.models.scope import Scope  # noqa: F401,E501


class Authorization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'description': 'str',
        'format': 'str',
        'required': 'list[str]',
        'properties': 'dict(str, SchemaObject)',
        'items': 'SchemaObject',
        'example': 'object',
        'discriminator': 'str',
        'pass_as': 'str',
        'keyname': 'str',
        'scopes': 'list[Scope]',
        'grant_types': 'GrantTypes',
        'ref': 'str',
        'default': 'object',
        'type': 'str',
        'enum': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'description': 'description',
        'format': 'format',
        'required': 'required',
        'properties': 'properties',
        'items': 'items',
        'example': 'example',
        'discriminator': 'discriminator',
        'pass_as': 'passAs',
        'keyname': 'keyname',
        'scopes': 'scopes',
        'grant_types': 'grantTypes',
        'ref': '$ref',
        'default': 'default',
        'type': 'type',
        'enum': 'enum'
    }

    def __init__(self, id=None, title=None, description=None, format=None, required=None, properties=None, items=None, example=None, discriminator=None, pass_as=None, keyname=None, scopes=None, grant_types=None, ref=None, default=None, type=None, enum=None):  # noqa: E501
        """Authorization - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._description = None
        self._format = None
        self._required = None
        self._properties = None
        self._items = None
        self._example = None
        self._discriminator = None
        self._pass_as = None
        self._keyname = None
        self._scopes = None
        self._grant_types = None
        self._ref = None
        self._default = None
        self._type = None
        self._enum = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if format is not None:
            self.format = format
        if required is not None:
            self.required = required
        if properties is not None:
            self.properties = properties
        if items is not None:
            self.items = items
        if example is not None:
            self.example = example
        if discriminator is not None:
            self.discriminator = discriminator
        if pass_as is not None:
            self.pass_as = pass_as
        if keyname is not None:
            self.keyname = keyname
        if scopes is not None:
            self.scopes = scopes
        if grant_types is not None:
            self.grant_types = grant_types
        if ref is not None:
            self.ref = ref
        if default is not None:
            self.default = default
        if type is not None:
            self.type = type
        if enum is not None:
            self.enum = enum

    @property
    def id(self):
        """Gets the id of this Authorization.  # noqa: E501

        An identifier  # noqa: E501

        :return: The id of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Authorization.

        An identifier  # noqa: E501

        :param id: The id of this Authorization.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Authorization.  # noqa: E501

        Schema title  # noqa: E501

        :return: The title of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Authorization.

        Schema title  # noqa: E501

        :param title: The title of this Authorization.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this Authorization.  # noqa: E501

        Description of the Schema  # noqa: E501

        :return: The description of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Authorization.

        Description of the Schema  # noqa: E501

        :param description: The description of this Authorization.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def format(self):
        """Gets the format of this Authorization.  # noqa: E501

        The format ex: int32, int64, float, double, byte, binary, date, date-time or password  # noqa: E501

        :return: The format of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this Authorization.

        The format ex: int32, int64, float, double, byte, binary, date, date-time or password  # noqa: E501

        :param format: The format of this Authorization.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def required(self):
        """Gets the required of this Authorization.  # noqa: E501

        Specifies if the parameter is required  # noqa: E501

        :return: The required of this Authorization.  # noqa: E501
        :rtype: list[str]
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this Authorization.

        Specifies if the parameter is required  # noqa: E501

        :param required: The required of this Authorization.  # noqa: E501
        :type: list[str]
        """

        self._required = required

    @property
    def properties(self):
        """Gets the properties of this Authorization.  # noqa: E501

        Not used beacause our model does not support inline nested types  # noqa: E501

        :return: The properties of this Authorization.  # noqa: E501
        :rtype: dict(str, SchemaObject)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Authorization.

        Not used beacause our model does not support inline nested types  # noqa: E501

        :param properties: The properties of this Authorization.  # noqa: E501
        :type: dict(str, SchemaObject)
        """

        self._properties = properties

    @property
    def items(self):
        """Gets the items of this Authorization.  # noqa: E501

        if the schema is an array specifies the items type  # noqa: E501

        :return: The items of this Authorization.  # noqa: E501
        :rtype: SchemaObject
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Authorization.

        if the schema is an array specifies the items type  # noqa: E501

        :param items: The items of this Authorization.  # noqa: E501
        :type: SchemaObject
        """

        self._items = items

    @property
    def example(self):
        """Gets the example of this Authorization.  # noqa: E501

        if the schema is an array specifies the items type  # noqa: E501

        :return: The example of this Authorization.  # noqa: E501
        :rtype: object
        """
        return self._example

    @example.setter
    def example(self, example):
        """Sets the example of this Authorization.

        if the schema is an array specifies the items type  # noqa: E501

        :param example: The example of this Authorization.  # noqa: E501
        :type: object
        """

        self._example = example

    @property
    def discriminator(self):
        """Gets the discriminator of this Authorization.  # noqa: E501


        :return: The discriminator of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._discriminator

    @discriminator.setter
    def discriminator(self, discriminator):
        """Sets the discriminator of this Authorization.


        :param discriminator: The discriminator of this Authorization.  # noqa: E501
        :type: str
        """

        self._discriminator = discriminator

    @property
    def pass_as(self):
        """Gets the pass_as of this Authorization.  # noqa: E501

        Denotes how the API key must be passed. Valid values are 'header' or 'query'.  # noqa: E501

        :return: The pass_as of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._pass_as

    @pass_as.setter
    def pass_as(self, pass_as):
        """Sets the pass_as of this Authorization.

        Denotes how the API key must be passed. Valid values are 'header' or 'query'.  # noqa: E501

        :param pass_as: The pass_as of this Authorization.  # noqa: E501
        :type: str
        """

        self._pass_as = pass_as

    @property
    def keyname(self):
        """Gets the keyname of this Authorization.  # noqa: E501

        The name of the header or query parameter to be used when passing the API key.  # noqa: E501

        :return: The keyname of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._keyname

    @keyname.setter
    def keyname(self, keyname):
        """Sets the keyname of this Authorization.

        The name of the header or query parameter to be used when passing the API key.  # noqa: E501

        :param keyname: The keyname of this Authorization.  # noqa: E501
        :type: str
        """

        self._keyname = keyname

    @property
    def scopes(self):
        """Gets the scopes of this Authorization.  # noqa: E501

        The list of OAuth scopes.  # noqa: E501

        :return: The scopes of this Authorization.  # noqa: E501
        :rtype: list[Scope]
        """
        return self._scopes

    @scopes.setter
    def scopes(self, scopes):
        """Sets the scopes of this Authorization.

        The list of OAuth scopes.  # noqa: E501

        :param scopes: The scopes of this Authorization.  # noqa: E501
        :type: list[Scope]
        """

        self._scopes = scopes

    @property
    def grant_types(self):
        """Gets the grant_types of this Authorization.  # noqa: E501

        The OAuth grant types.  # noqa: E501

        :return: The grant_types of this Authorization.  # noqa: E501
        :rtype: GrantTypes
        """
        return self._grant_types

    @grant_types.setter
    def grant_types(self, grant_types):
        """Sets the grant_types of this Authorization.

        The OAuth grant types.  # noqa: E501

        :param grant_types: The grant_types of this Authorization.  # noqa: E501
        :type: GrantTypes
        """

        self._grant_types = grant_types

    @property
    def ref(self):
        """Gets the ref of this Authorization.  # noqa: E501

        A Reference to a definition on definitions object  # noqa: E501

        :return: The ref of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this Authorization.

        A Reference to a definition on definitions object  # noqa: E501

        :param ref: The ref of this Authorization.  # noqa: E501
        :type: str
        """

        self._ref = ref

    @property
    def default(self):
        """Gets the default of this Authorization.  # noqa: E501

        Default value for this schema if it is applicable  # noqa: E501

        :return: The default of this Authorization.  # noqa: E501
        :rtype: object
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this Authorization.

        Default value for this schema if it is applicable  # noqa: E501

        :param default: The default of this Authorization.  # noqa: E501
        :type: object
        """

        self._default = default

    @property
    def type(self):
        """Gets the type of this Authorization.  # noqa: E501

        The authorization type.  One of: basicAuth, apiKey, oauth2, none  # noqa: E501

        :return: The type of this Authorization.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Authorization.

        The authorization type.  One of: basicAuth, apiKey, oauth2, none  # noqa: E501

        :param type: The type of this Authorization.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def enum(self):
        """Gets the enum of this Authorization.  # noqa: E501


        :return: The enum of this Authorization.  # noqa: E501
        :rtype: list[str]
        """
        return self._enum

    @enum.setter
    def enum(self, enum):
        """Sets the enum of this Authorization.


        :param enum: The enum of this Authorization.  # noqa: E501
        :type: list[str]
        """

        self._enum = enum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Authorization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Authorization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
